# Stage 1: React

FROM node:18-alpine as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install --silent

ARG API_URL
ENV REACT_APP_API_URL=$API_URL
ENV NODE_OPTIONS=--max_old_space_size=2048
ENV GENERATE_SOURCEMAP=false
ENV PATH /app/node_modules/.bin:$PATH

COPY . .

RUN npm run build


# Stage 2: Nginx

FROM nginx:latest

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]