version: "3"

services:
    mongo:
        container_name: mongodb
        image: mongo
        env_file: .env
        volumes:
            - data-volume:/data/db

    server:
        container_name: backend
        image: xclone-backend
        env_file: .env
        build:
            context: server
            dockerfile: Dockerfile
        ports:
            - $SERVER_PORT:$SERVER_PORT
        volumes:
            - ./server/:/app
            - /app/node_modules
        depends_on:
            - mongo

    client:
        container_name: frontend
        image: xclone-frontend
        env_file: .env
        build:
            context: client
            dockerfile: Dockerfile
            args:
                - SERVER_ORIGIN=$SERVER_ORIGIN
        ports:
            - $CLIENT_PORT:$CLIENT_PORT
        volumes:
            - ./client/:/app
            - /app/node_modules
        depends_on:
            - server

volumes:
    data-volume:
