version: "1.5"

services:
    mongo:
        image: mongo
        container_name: mongodb
        env_file: ./.env
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db

    server:
        container_name: backend
        image: xclone-backend
        env_file: ./.env
        build:
            context: ./server
            dockerfile: Dockerfile
            args:
                - DOCKER_PORT=$SERVER_DOCKER_PORT
        ports:
            - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
        volumes:
            - ./server/:/app
            - /app/node_modules
        depends_on:
            - mongo

    client:
        container_name: frontend
        image: xclone-frontend
        env_file: ./.env
        build:
            context: ./client
            dockerfile: Dockerfile
            args:
                - SERVER_ORIGIN=$SERVER_ORIGIN
                - DOCKER_PORT=$CLIENT_DOCKER_PORT
        ports:
            - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
        volumes:
            - ./client/:/app
            - /app/node_modules
        depends_on:
            - server

volumes:
    data-volume:
